name: flysystem
label: Flysystem
description: Multi-disk filesystem via openpeeps/flysystem (atomic writes, policies)
url: https://github.com/openpeeps/flysystem
requires:
  - flysystem >= 0.2.0
files:
  - dest: src/service/provider/flysystem.nim
    source: flysystem.nim
  - dest: config/flysystem.yml
    source: flysystem.yml
init: flysystem.init()
