# Supra CLI - A command-line interface for managing
# your Supranim applications and projects
#
#   (c) 2026 MIT License | Made by Humans from OpenPeeps
#   https://supranim.com | https://github.com/supranim

import std/[os, strutils, sequtils, algorithm, times]
import pkg/kapsis/runtime
import pkg/kapsis/interactive/[spinny, widgets, prompts]

## This module implements the `supra bundle` command which provides
## utilities for bundling static assets into a Nim application.
## 
## It generates a .nim file with an embedded byte string and an
## index of the file metadata, as well as a .bin file containing the
## raw data. The generated .nim file can be imported into the
## application to serve assets from memory without filesystem access.
## 
## This is particularly useful for web applications that need to serve
## static content efficiently.
## 
## The bundling process includes a heuristic to determine if files are
## plain text or binary, allowing for optimized handling of text assets.
## 
## This command is designed to be used in the build process of a Supranim
## application, typically invoked from a build script or as part of a CI/CD pipeline.

type
  Entry = object
    key: string
    off: int
    size: int
    isText: bool

proc isPlainText(data: string, sampleSize = 8192): bool =
  let n = min(data.len, sampleSize)
  if n == 0: return true
  var ctrl = 0
  for i in 0..<n:
    let b = uint8(ord(data[i]))
    if b == 0'u8: return false
    if (b < 9'u8) or (b >= 14'u8 and b < 32'u8) or (b == 127'u8):
      inc ctrl
  (ctrl * 100 div n) <= 2

proc nimStringLiteral(s: string): string =
  result = "\""
  for ch in s:
    case ch
    of '\\': result.add("\\\\")
    of '\"': result.add("\\\"")
    of '\n': result.add("\\n")
    of '\r': result.add("\\r")
    of '\t': result.add("\\t")
    else:
      let o = ord(ch)
      if o < 32:
        result.add("\\x" & toHex(o, 2))
      else:
        result.add(ch)
  result.add("\"")

proc writeIfChanged(path, content: string) =
  # write content to path only if it has changed to avoid
  # unnecessary rebuilds
  if fileExists(path):
    let prev = readFile(path)
    if prev == content:
      return
  writeFile(path, content)

proc bundleAssetsCommand*(v: Values) =
  ## Bundles static assets from a directory into a .nim file with an embedded byte
  ## string and an index of asset metadata.
  let dirArg = v.get("dir").getStr
  let outArg = v.get("output").getStr

  let baseDir = getCurrentDir()
  let srcDir = if dirArg.isAbsolute: dirArg else: absolutePath(baseDir / dirArg)
  let outNim = if outArg.isAbsolute: outArg else: absolutePath(baseDir / outArg)
  let outBin = changeFileExt(outNim, "bin")
  let keyPrefix = srcDir.lastPathPart.replace("\\", "/")   # "assets"

  if not dirExists(srcDir):
    raise newException(IOError, "Assets directory does not exist: " & srcDir)

  let outParent = parentDir(outNim)
  if outParent.len > 0:
    createDir(outParent)

  var files: seq[string] = @[]
  for f in walkDirRec(srcDir):
    let relToSrc = relativePath(f, srcDir).replace("\\", "/")
    if relToSrc.isHidden(): continue
    files.add(f)
  files.sort(system.cmp[string])

  var entries: seq[Entry] = @[]
  var blob = newStringOfCap(1024 * 64)
  var off = 0

  for f in files:
    let relToSrc = relativePath(f, srcDir).replace("\\", "/")
    let key = "/" & (keyPrefix / relToSrc).replace("\\", "/")    # "assets/app.css"
    let raw = readFile(f)
    entries.add(Entry(key: key, off: off,
        size: raw.len, isText: isPlainText(raw)))
    blob.add(raw)
    off += raw.len
  writeIfChanged(outBin, blob)

  var lines: seq[string] = @[]
  lines.add("# generated by Supra CLI via `supra bundle.assets` command")
  lines.add("# last updated: " & $now())
  lines.add("# source: " & srcDir)
  lines.add("const supraBlob = staticRead(" & nimStringLiteral(outBin) & ")")
  lines.add("const supraIndex = [")
  for e in entries:
    lines.add("  (" &
      nimStringLiteral(e.key) & ", " &
      $e.off & ", " &
      $e.size & ", " &
      (if e.isText: "true" else: "false") &
      "),")
  lines.add("]")
  lines.add("""
proc supraToBytes(s: string, off, size: int): seq[uint8] =
  # Convert a substring of `s` to a sequence of bytes without copying if possible
  result = newSeq[uint8](size)
  if size > 0:
    copyMem(result[0].addr, s[off].unsafeAddr, size)

block initAssets:
  # Initialize the StaticBundle with the embedded assets
  let sta = staticAssets()
  # Fast path for binary assets; fallback to byte->string copy
  for e in supraIndex:
    let key = e[0]
    let off = e[1]
    let size = e[2]
    let isText = e[3]
    if isText:
      if size == 0: sta.addTextAsset(key, "")
      else: sta.addTextAsset(key, supraBlob[off ..< off + size])
    else:
      sta.addAsset(key, supraToBytes(supraBlob, off, size))
""")

  writeIfChanged(outNim, lines.join("\n"))
  displaySuccess("Supra Assets Bunndler generated successfully (" & $entries.len & " files)")
  display("Source: " & srcDir, indent = 2)
  display("Output: " & outNim, indent = 2)