name: openparser/svg
label: openparser/svg
description: SVG parsing and serialization via openpeeps/openparser
url: https://github.com/openpeeps/openparser
requires:
  - openparser >= 0.3.5
files:
  - dest: src/service/provider/openparser_svg.nim
    source: openparser_svg.nim
