name: openparser/feed
label: openparser/feed
description: Atom feed parsing via openpeeps/openparser
url: https://github.com/openpeeps/openparser
requires:
  - openparser >= 0.3.5
files:
  - dest: src/service/provider/openparser_feed.nim
    source: openparser_feed.nim
